### ISSUE TITLE
Implement versioneer support for automatic version string updates

### ISSUE THREAD

**Issue by kiudee** [kiudee/cs-ranking#70]
Rationale
---------
Updating the version string when doing a new release is error-prone. [Versioneer](https://github.com/warner/python-versioneer) automatically determines the version string by querying git.
This allows us to simply tag a commit using a descriptive name like `v1.1` or `1.1` and it will be applied automatically.

**Comment by timokau** [comment]
I have read through the versioneer readme and installation instructions and opened https://github.com/kiudee/cs-ranking/pull/79 as a POC.

However, I'm not convinced that we should do this. There are multiple reasons:

- versioneer hasn't seen a commit in [some time](https://github.com/warner/python-versioneer/commit/6b555078bec6286dbbb46f8ae9c775597e162186), it seems unmaintained. You could argue that maybe it just doesn't need very much maintenance, but `versioneer install` already shows a deprecation warning:

```
versioneer.py:342: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
  parser = configparser.SafeConfigParser()
```

- it adds a lot of complexity (2.3k lines of code) for a very simple problem. Also one now needs to run code to find out the version, instead of being able to figure it out statically.

- it relies on either VCS information being available at runtime or some [magic](https://www.git-scm.com/docs/gitattributes#_code_export_subst_code) of the `git-archive` command. When doing something else, like just stripping the `.git` directory, this will [break](https://github.com/NixOS/nixpkgs/pull/54684) (its just a coincidence that I'm involved in that PR -- I didn't remember it, I just searched for issues with versioneer).

- A similar point applies if we want to change VCS at some point. Old versions would cease to work.

- It just seems a bit wrong to me to depend on the VCS at runtime. I feel like the VCS should know about the code, but the code should be agnostic to the VCS.


None of these are very strong reasons not to use versioneer, but is there a strong reason to use it?
